package sk.stuba.fei.uim.oop;
import java.util.Objects;

public class Figure {

    private String colorName;//"GREEN, CYAN..."

    public String getColorCode() {
        return colorCode;
    }

    private String colorCode;
    private char shape; // shape of figure is represented as single character for now

    public Figure(){}


    @Override //generated by Intellij
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Figure figure = (Figure) o;
        return shape == figure.shape && Objects.equals(colorName, figure.colorName);
    }//actually this is smart


    @Override
    public int hashCode() {
        return Objects.hash(colorName, shape);
    }

    public Figure(String colorName, char shape) {
        this.colorName = colorName;
        this.colorCode = ConsoleColors.colorsMap.get(colorName);
        this.shape = shape;
    }


    public String getColorName() {
        return colorName;
    }
    public char getShape() {
        return shape;
    }

    public void setShape(char c) {
        this.shape = c;
    }

    public String renderString() {
        return colorCode+shape+ConsoleColors.RESET;
    }
}
